routes/web.php
<?php

use App\Http\Controllers\ProfilController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;



Route::get('/', 'DashboardController@dash')->name('dashboard');

Route::get('/commandes/{id}/statut', 'CommandeController@changeStatut')->name('commandeStatut');

Route::patch('/commandes/{id}/statut', 'CommandeController@statutAdmin')->name('statut.admin');

Route::get('pdf/{id}','CommandeController@gen')->name('pdf.gen');

Route::get('/search', 'CommandeController@search')->name('commande.search');

Route::get('/commandes/filter', 'CommandeController@filter')->name('commande.filter');

Route::resource('/commandes','CommandeController')->except([
    'create', 'edit'
]);

Route::resource('/produit','ProduitController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::resource('/reception','ReceptionController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::get('/reception/{id}/valide','ReceptionController@valide')->name('reception.valide')->middleware('can:manage-users');

Route::get('showFromNotify/{commande}/{notification}' , 'CommandeController@showFromNotify')->name('commandes.showFromNotify');

Route::get('showFromNotify/{reception}/{notification}' , 'ReceptionController@showFromNotify')->name('reception.showFromNotify');


Route::get('/profil', 'ProfilController@index')->name('profil.index');

Route::match(['put', 'patch'],'/profil/{user}', 'ProfilController@update')->name('profil.update');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bonlivraison','BonLivraisonController')->only([
    'index', 'store'
]);

Route::get('/bonlivraison/{id}/infos','BonLivraisonController@infos')->name('bon.infos');

Route::get('/bonlivraison/{id}/pdf','BonLivraisonController@gen')->name('bon.gen');

Route::get('/bonlivraison/{id}/details','BonLivraisonController@search')->name('bon.search');

Route::resource('/facture','FactureController')->only([
    'index', 'store'
]);

Route::get('/facture/{id}/pdf','FactureController@gen')->name('facture.gen');

Route::get('/facture/{id}/details','FactureController@search')->name('facture.search');

Route::get('/facture/{id}/infos','FactureController@infos')->name('facture.infos');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users','UsersController',['except' => ['show','create','store']]);
});

Route::get('/facture/{id}/send','EmailController@sendFacture')->name('email.facture')->middleware('can:ramassage-commande');

Route::get('/inbox','NotificationController@index')->name('inbox.index');
Route::get('/{notifications}/show','NotificationController@show')->name('inbox.show');
Route::get('/{notifications}/delete','NotificationController@destroy')->name('inbox.destroy');

resources/views/404.blade.php
@extends('racine')

@section('content')

test 404
    
@endsection

resources/views/bonLivraison.blade.php
@extends('racine')

@section('title')
    Bon de Livraison
@endsection




@section('style')
    <style>
        .page-link {
            color: #e85f03 !important;
        }
        .page-item.active .page-link {
            background-color: #e85f03 !important;
            border-color: #e85f03 !important;
            color: #fff !important;
        }
    </style>
@endsection


@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        @if (session()->has('search'))
        <div class="alert alert-dismissible alert-warning col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Oupss !</strong> Il n'existe aucun numero de bon de commande avec : {{session()->get('search')}}  </a>.
          </div>
        @endif
        @if (session()->has('cmdExist'))
        <div class="alert alert-dismissible alert-danger col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Erreur ! </strong>vous ne pouvez pas charger le bon de livraison avec 0 commande ramassée !
          </div>
        @endif
        @if (session()->has('blNoExist'))
        <div class="alert alert-dismissible alert-danger col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Erreur ! </strong>Le bon de livraison d'aujourd'hui à été déjà générer !
          </div>
        @endif
        @if (session()->has('ajoute'))
        <div class="alert alert-dismissible alert-success col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Et voilà ! </strong>Le bon de livraison d'aujourd'hui à été bien générer !
          </div>
        @endif
      
        <div class="col-5">
            <h4 class="page-title">Bon de livraison</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Bon de livraison</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-7">
            <div class="text-right upgrade-btn">
                @can('ramassage-commande')
                <a  class="btn btn-danger text-white"  data-toggle="modal" data-target="#modalBonLivraison"><i class="fa fa-plus-square">
                    </i> Générer le bon de livraison
                </a>

                </select>
                @endcan
                @cannot('ramassage-commande')
                
                    <button data-toggle="modal" data-target="#genererBon"type="submit" class="btn btn-danger text-white m-r-5"><i class="fa fa-plus-square"></i> Générer le bon de livraison</button>
                @endcan
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            <div class="card-header">{{ __('Total des Bons de livraison : ') }} {{ $total }}</div>

                <div class="card-body ">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                              <tr>
                                @can('ramassage-commande')
                                <th scope="col">#</th>
                                @endcan
                                <th scope="col">Code</th>
                                <th scope="col">Commandes ramassées</th>
                                <th scope="col">Nombre de Colis</th>
                                <th scope="col">Date d'ajout</th>
                                <th scope="col">Montant Total</th>
                                <th scope="col">Frais de Livraison</th>
                                <th scope="col">Imprimer</th>
                              
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ($bonLivraisons as $index => $bonLivraison)
                              <tr 
                              @if (\Carbon\Carbon::parse($bonLivraison->created_at)->format('d-m-Y') == date("d-m-Y") && session()->has('bonLivraison') )
                              style="background-color: #e85f032e;"
                              @endif
                              >
                                @can('ramassage-commande')
                                <th scope="row"><img src="{{$users[$index]->image}}" alt="user" class="rounded-circle" width="31"></th>
                                @endcan
                                <th>
                                  <a class="btn btn-light" href="{{route('bon.search',$bonLivraison->id)}}">
                                    BL_{{bin2hex(substr($users[$index]->name, - strlen($users[$index]->name) , 3)).$bonLivraison->id}}
                                  </a>
                                  
                                </th>
                                <td>{{$bonLivraison->commande}}</td>
                                <td>{{$bonLivraison->colis}}</td>
                                <td>{{ $bonLivraison->created_at}}</td>
                                <td>{{ $bonLivraison->montant}} Mad</td>
                                <td>{{ $bonLivraison->prix}} Mad</td>
                                <td>
                                <a target="_blank" class="btn btn-info text-white m-r-5" href="{{route('bon.gen',$bonLivraison->id)}}" >
                                  <i class="fas fa-print"></i></a>
                               </td>
                             
                            </tr>
                              @endforeach
    
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="container my-4">    
    <div class="modal fade" id="modalBonLivraison" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header text-center">
                          <h4 class="modal-title w-100 font-weight-bold">Choisissez le fournisseur</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body mx-3">
                            <form class="form-horizontal form-material" method="POST" action="{{route('bonlivraison.store')}}">
                                @csrf
                                
                                
                                <div class="form-group">
                                    <label for="client" class="col-sm-12">Fournisseur :</label>
                                    <div class="col-sm-12">
                                        <select name="client" id="client" class="form-control form-control-line" value="{{ old('client') }}">
                                            <option value="" disabled selected>Choisissez le fournisseur</option>
                                            @foreach ($clients as $client)
                                        <option value="{{$client->id}}" class="rounded-circle">
                                            {{$client->name}}
                                        </option>
                                            @endforeach
                                           
                                        </select>
                                        
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="modal-footer d-flex justify-content-center">
                                        <button class="btn btn-warning">Générer</button>
                                        
                                    </div>
                                </div>
                            </form>
                            @if ($errors->any())
                            <div class="alert alert-dismissible alert-danger">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>
                                        <strong>{{$error}}</strong>
                                        </li>
                                    @endforeach
                                </ul>
                              </div>
                              @endif
                        </div>
            
                      </div>
                    </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="genererBon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Êtes-vous sûr de générer le bon de livraison pour ce jour?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Voud avez {{$ramasse}} de commandes Rammassées sur {{$nonRamasse + $ramasse}} commandes expidiées
        </div>
        <div class="modal-body">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                NB: Aprés la génération du bon de livraison vous ne pourrez pas <strong>ajouter une nouvelle commande</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
          <form method="POST" action="{{ route('bonlivraison.store') }}">
            @csrf
            <button data-toggle="modal" data-target="#genererBon"type="submit" class="btn btn-danger text-white m-r-5">générer</button>
        </form>
        </div>
      </div>
    </div>
  </div>


@endsection

@section('javascript')
    @if ($errors->any())
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#modalSubscriptionForm').modal('show');
            });
        </script>
    @endif
@endsection

resources/views/facture.blade.php
@extends('racine')

@section('title')
    Gestion des factures
@endsection




@section('style')
    <style>
        .page-link {
            color: #e85f03 !important;
        }
        .page-item.active .page-link {
            
            background-color: #e85f03 !important;
            border-color: #e85f03 !important;
            color: #fff !important;
        }
    </style>
@endsection


@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        @if (session()->has('search'))
        <div class="alert alert-dismissible alert-warning col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Oupss !</strong> Il n'existe aucun numero de facture avec : {{session()->get('search')}}  </a>.
          </div>
        @endif
        @if (session()->has('nbrCmdLivre'))
        <div class="alert alert-dismissible alert-danger col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Erreur ! </strong>vous ne pouvez pas charger la facture avec 0 commande livrée !
          </div>
        @endif
        @if (session()->has('nbrCmdRamasse'))
        <div class="alert alert-dismissible alert-danger col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Erreur ! </strong>vous ne pouvez pas charger la facture avec sans traité tous les commandes ! <br>
        Il vous reste {{session()->get('nbrCmdRamasse')}} à traiter !
          </div>
        @endif

        @if (session()->has('facNoExist'))
        <div class="alert alert-dismissible alert-danger col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Erreur ! </strong>Cette facture à été déjà générée !
          </div>
        @endif

        @if (session()->has('ajoute'))
        <div class="alert alert-dismissible alert-success col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Et voilà ! </strong>La facture à été bien généner !
          </div>
        @endif
        @if (session()->has('envoyer'))
        <div class="alert alert-dismissible alert-success col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Wééé !</strong> La facture à été bien envoyer à  : {{session()->get('envoyer')}}  </a>.
          </div>
        @endif
        <div class="col-5">
            <h4 class="page-title">Gestion des factures</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Facture</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-7">
            <div class="text-right upgrade-btn">
                @can('ramassage-commande')
                <a  class="btn btn-danger text-white"  data-toggle="modal" data-target="#modalfacture"><i class="fa fa-plus-square">
                    </i> Générer la facture
                </a>

                </select>
                @endcan
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            <div class="card-header">{{ __('Total des Factures générées : ') }} {{ $total }}</div>

                <div class="card-body ">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                              <tr>
                                @can('ramassage-commande')
                                <th scope="col">#</th>
                                @endcan
                                <th scope="col">Code</th>
                                <th scope="col">Commandes livrées</th>
                                <th scope="col">Montant Total</th>
                                <th scope="col">Frais de Livraison</th>
                                <th scope="col">Commandes non livrées</th>
                                <th scope="col">Colis non livrés</th>
                                <th scope="col">Date d'ajout</th>
                                <th scope="col">Imprimer la facture</th>
                                @can('ramassage-commande')
                                <th scope="col">Envoyer par mail</th>
                                @endcan
                              
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ($factures as $index => $facture)
                              <tr>
                                @can('ramassage-commande')
                                <th scope="row"><img src="{{$users[$index]->image}}" alt="user" class="rounded-circle" width="31"></th>
                                @endcan
                                <th>
                                    <a class="btn btn-light" href="{{route('facture.search',$facture->id)}}">
                                        {{$facture->numero}}
                                    </a>
                                </th>
                                <td>{{ $facture->livre}}</td>
                                <td>{{ $facture->montant}} Mad</td>
                                <td>{{ $facture->prix}} Mad</td>
                                <td>{{$facture->commande}}</td>
                                <td>{{$facture->colis}}</td>
                                <td>{{ $facture->created_at}}</td>
                                <td>
                                    <a class="btn btn-warning text-white m-r-5" href="{{route('facture.gen',$facture->id)}}" target="_blank"><i class="mdi mdi-printer"></i></a>
                                </td>
                                @can('ramassage-commande')
                                <td>
                                    <a class="btn btn-info text-white m-r-5" href="{{route('email.facture',$facture->id)}}" ><i class="mdi mdi-send"></i></a>
                                </td>
                                @endcan
                            </tr>
                              @endforeach
    
                            </tbody>
                          </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="container my-4">    
    <div class="modal fade" id="modalfacture" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header text-center">
                          <h4 class="modal-title w-100 font-weight-bold">Choisissez le fournisseur</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body mx-3">
                            <form class="form-horizontal form-material" method="POST" action="{{route('facture.store')}}">
                                @csrf
                                
                                
                                <div class="form-group">
                                    <label for="client" class="col-sm-12">Fournisseur :</label>
                                    <div class="col-sm-12">
                                        <select name="client" id="client" class="form-control form-control-line" value="{{ old('client') }}" required>
                                            <option value="" disabled selected>Choisissez le fournisseur</option>
                                            @foreach ($clients as $client)
                                        <option value="{{$client->id}}" class="rounded-circle">
                                            {{$client->name}}
                                        </option>
                                            @endforeach
                                           
                                        </select>
                                        
                                    </div>
                                </div>
                            

                                <div class="form-group">
                                    <div class="modal-footer d-flex justify-content-center">
                                        <button class="btn btn-warning">Générer</button>
                                        
                                    </div>
                                </div>
                            </form>
                            @if ($errors->any())
                            <div class="alert alert-dismissible alert-danger">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>
                                        <strong>{{$error}}</strong>
                                        </li>
                                    @endforeach
                                </ul>
                              </div>
                              @endif
                        </div>
            
                      </div>
                    </div>
    </div>
</div>


@endsection

@section('javascript')
    @if ($errors->any())
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#modalSubscriptionForm').modal('show');
            });
        </script>
    @endif
@endsection

resources/views/profil.blade.php
@extends('racine')

@section('title')
{{$user->name}} | Quickoo
@endsection

@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-5">
            <h4 class="page-title">Profile Page</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Quickoo</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Profile</li>
                    </ol>
                </nav>
            </div>
        </div>
  
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <!-- Row -->
    <div class="row">
        <!-- Column -->
        <div class="col-lg-4 col-xlg-3 col-md-5">
            <div class="card">
                <div class="card-body">
                <center class="m-t-30"> <img src="{{$user->image}}" class="rounded-circle" width="150" />
                        <h4 class="card-title m-t-10">{{$user->name}}</h4>
                        <h6 class="card-subtitle">ICE: {{$user->description}}</h6>
                        <div class="row text-center justify-content-md-center">
                        <div class="col-4"><a href="{{route('commandes.index')}}" class="link"><i class="icon-people"></i> <font class="font-medium">{{$total}} <br>Commandes</font></a></div>
                            <div class="col-4"><a href="{{route('facture.index')}}" class="link"><i class="icon-picture"></i> <font class="font-medium">{{$facture}} <br>Factures</font></a></div>
                        </div>
                    </center>
                </div>
                <div>
                    <hr> </div>
                <div class="card-body"> <small class="text-muted">Addresse email </small>
                    <h6>{{$user->email}}</h6> <small class="text-muted p-t-30 db">Téléphone</small>
                    <h6>{{$user->telephone}}</h6> <small class="text-muted p-t-30 db">Addresse</small>
                    <h6>{{$user->adresse}}</h6>
                    <div class="map-box">
                        <iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Marjane,%20Tanger%20PAC,%20Avenue%20des%20Forces%20Arm%C3%A9es%20Royales,%20Tanger%2090060+(Decathlon%20Tanger)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" width="100%" height="150" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div> <small class="text-muted p-t-30 db">Reseaux Sociaux</small>
                    <br/>
                    <a href="https://www.facebook.com/DeliveryQuickoo" target="_blank" class="btn btn-circle btn-secondary"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://www.instagram.com/DeliveryQuickoo" target="_blank" class="btn btn-circle btn-secondary"><i class="fab fa-instagram"></i></a>
                    <a href="https://www.linkedin.com/company/quickoo/" target="_blank" class="btn btn-circle btn-secondary"><i class="fab fa-linkedin"></i></a>
                </div>
            </div>
        </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-lg-8 col-xlg-9 col-md-7">
            <div class="card">
                <div class="card-body">
                    <form class="form-horizontal form-material" method="POST" action="{{route('profil.update',$user)}}">
                        @csrf
                        @method("PUT")
                        <div class="form-group">
                            <label for="name" class="col-md-12">Nom & Prénom: </label>

                        <div class="col-md-12">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required  autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-12">Email: </label>

                            <div class="col-md-12">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required>
    
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Url de l'image</label>
                            <div class="col-md-12">
                                <input name="image" type="text" value="{{$user->image}}"class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Téléphone</label>
                            <div class="col-md-12">
                            <input name="telephone" type="text" value="{{$user->telephone}}" class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Adresse</label>
                            <div class="col-md-12">
                            <textarea name="adresse" rows="5" class="form-control form-control-line">{{$user->adresse}}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12">Ville</label>
                            <div class="col-md-12">
                                <input name="ville" type="text" value="{{$user->ville}}" class="form-control form-control-line">
                                </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-success">Modifier</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Column -->
    </div>

</div>
@endsection