routes/web.php
<?php

use App\Http\Controllers\ProfilController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;



Route::get('/', 'DashboardController@dash')->name('dashboard');

Route::get('/commandes/{id}/statut', 'CommandeController@changeStatut')->name('commandeStatut');

Route::patch('/commandes/{id}/statut', 'CommandeController@statutAdmin')->name('statut.admin');

Route::get('pdf/{id}','CommandeController@gen')->name('pdf.gen');

Route::get('/search', 'CommandeController@search')->name('commande.search');

Route::get('/commandes/filter', 'CommandeController@filter')->name('commande.filter');

Route::resource('/commandes','CommandeController')->except([
    'create', 'edit'
]);

Route::resource('/produit','ProduitController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::resource('/reception','ReceptionController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::get('/reception/{id}/valide','ReceptionController@valide')->name('reception.valide')->middleware('can:manage-users');

Route::get('showFromNotify/{commande}/{notification}' , 'CommandeController@showFromNotify')->name('commandes.showFromNotify');

Route::get('showFromNotify/{reception}/{notification}' , 'ReceptionController@showFromNotify')->name('reception.showFromNotify');


Route::get('/profil', 'ProfilController@index')->name('profil.index');

Route::match(['put', 'patch'],'/profil/{user}', 'ProfilController@update')->name('profil.update');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bonlivraison','BonLivraisonController')->only([
    'index', 'store'
]);

Route::get('/bonlivraison/{id}/infos','BonLivraisonController@infos')->name('bon.infos');

Route::get('/bonlivraison/{id}/pdf','BonLivraisonController@gen')->name('bon.gen');

Route::get('/bonlivraison/{id}/details','BonLivraisonController@search')->name('bon.search');

Route::resource('/facture','FactureController')->only([
    'index', 'store'
]);

Route::get('/facture/{id}/pdf','FactureController@gen')->name('facture.gen');

Route::get('/facture/{id}/details','FactureController@search')->name('facture.search');

Route::get('/facture/{id}/infos','FactureController@infos')->name('facture.infos');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users','UsersController',['except' => ['show','create','store']]);
});

Route::get('/facture/{id}/send','EmailController@sendFacture')->name('email.facture')->middleware('can:ramassage-commande');

Route::get('/inbox','NotificationController@index')->name('inbox.index');
Route::get('/{notifications}/show','NotificationController@show')->name('inbox.show');
Route::get('/{notifications}/delete','NotificationController@destroy')->name('inbox.destroy');

app/Produit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produit extends Model
{
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function stock(){
        return $this->hasOne('App\Stock');
    }

 

      public function mouvements(){
        return $this->hasMany('App\Mouvement');
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Commande;
use App\Http\Requests\StoreCommande;
use App\Notifications\newCommande;
use App\Notifications\statutChange;
use App\Statut;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use App\User;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Support\Facades\Auth;
use App\Produit;
use App\Stock;
use Illuminate\Http\Request;

class ProduitController extends Controller
{

      /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = [] ;
        $stock = [];
        if(!Gate::denies('ramassage-commande')) {
            //session administrateur donc on affiche tous les commandes
            $total = DB::table('produits')->count();
            $produits= DB::table('produits')->orderBy('created_at', 'DESC')->paginate(10);
            foreach($produits as $produit){
                if(!empty(User::find($produit->user_id)))
                $users[] =  User::find($produit->user_id) ;
            }
            //dd($clients[0]->id);
        }
        else{
            $produits= DB::table('produits')->where('user_id',Auth::user()->id )->orderBy('created_at', 'DESC')->paginate(10);
            $total =DB::table('produits')->where('user_id',Auth::user()->id )->count();
            
        }
        foreach($produits as $produit){
            $dbStock = DB::table('stocks')->where('produit_id',$produit->id)->first();
            $stock[] =  $dbStock ;
        }

        return view('produit.index' , ['produits' => $produits, 
                                    'total'=>$total,
                                    'users'=> $users,
                                    'stock'=>$stock]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(Gate::denies('ecom')){
           
                return redirect('/commandes');
            } 
            else{
                $produit = new Produit();
                
                $produit->libelle = $request->libelle;
                $produit->prix = $request->prix;
                $produit->categorie = $request->categorie;
                $produit->description = $request->description;
                $produit->reference = bin2hex(substr($produit->libelle, - strlen($produit->libelle) , 3)).date("mdis");
                //dd($request);
                if ($request->hasfile('photo')){
                   //dd($request->file('photo'));
                    $file = $request->file('photo');
                    $extension = $file->getClientOriginalExtension(); //getting image extension
                    $filename = time() . '.' . $extension ;
                    $file->move('uploads/produit/',$filename);
                    $produit->photo = $filename ;
                }
                else{
                    $produit->photo =  $produit->categorie . '.png';
                }

                $produit->user()->associate(Auth::user())->save();

                $stock = new Stock();

                $stock->qte = 0;
                $stock->cmd = 0;
                $stock->etat = "Nouveau";
                $stock->produit()->associate($produit)->save();
                return redirect()->route('produit.index');
            }
            
        
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function show(Produit $produit)
    {
        if(Gate::denies('ramassage-commande')){
            if($produit->user_id !== Auth::user()->id)
            return redirect()->route('produit.index');
        }
        $stock = DB::table('stocks')->where('produit_id',$produit->id)->first();
        return view('produit.show', ['produit'=>$produit ,
                                    'stock' =>$stock
                                    ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function edit(Produit $produit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Produit $produit)
    {
        if((!Gate::denies('ecom') && $produit->user_id !== Auth::user()->id ) || Gate::denies('gestion-stock')){
            return redirect()->route('produit.index');
        }
        else{
            $produit->libelle = $request->libelle;
            $produit->prix = $request->prix;
            $produit->categorie = $request->categorie;
            $produit->description = $request->description;
            if ($request->hasfile('photo')){
                 $file = $request->file('photo');
                 $extension = $file->getClientOriginalExtension(); //getting image extension
                 $filename = time() . '.' . $extension ;
                 $file->move('uploads/produit/',$filename);
                 $produit->photo = $filename ;
             }
             $produit->save();
               
             $request->session()->flash('produit', 'modifié');

             return redirect()->route('produit.show',['produit' => $produit->id]);
        }
        
        
        dd("salut");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produit $produit)
    {
        //
    }
}

resources/views/produit/index.blade.php
@extends('racine')

@section('title')
   Gestion de stock
@endsection

@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-5">
            <h4 class="page-title">Gestion de stock</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Stock</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-7">
        <div class="row float-right d-flex ">
            <div class=m-r-5" style="margin-right: 10px;">
                <a  class="btn btn-warning text-white"  data-toggle="modal" data-target="#modalStockSearch"><i class="fa fa-search"></i></a>
            </div>
            @can('gestion-stock')
            <div class="m-r-5">
                <a  class="btn btn-danger text-white"  data-toggle="modal" data-target="#modalStockAdd"><i class="fa fa-plus-square"></i> Ajouter</a>
            </div>
            @endcan
        </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Gerer votre stock</h4>
                    <h6 class="card-subtitle">Nombre total de vos articles : <code>{{$total}} Articles</code> .</h6>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered" style="font-size: 0.85em;">
                        <thead>
                            <tr>
                                @can('ramassage-commande')
                                <th scope="col">Client</th>
                                @endcan
                                <th scope="col">Image</th>
                                <th scope="col">Reference</th>
                                <th scope="col">Libelle</th>
                                <th scope="col">Categorie</th>
                                <th scope="col">Prix</th>
                                <th scope="col">Quantité</th>
                                <th scope="col">En commande</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                           @forelse ($produits as $index => $produit)
                           <tr>
                            @can('ramassage-commande')
                            <th scope="row">
                                <a title="{{$users[$index]->name}}" class=" text-muted waves-effect waves-dark pro-pic" 
                                       
                                            @can('edit-users')
                                                href="{{route('admin.users.edit',$users[$index]->id)}}"
                                            @endcan

                                        
                                    >
                                    <img src="{{$users[$index]->image}}" alt="user" class="rounded-circle" width="31">
                                </a>
                            </th>
                            @endcan

                            <th scope="row"> <a title="{{$produit->reference}}" class=" text-muted waves-effect waves-dark pro-pic">
                                    <img src="/uploads/produit/{{$produit->photo}}" alt="user" class="rounded-circle" width="31">
                                </a></th>
                            <td>{{$produit->reference}}</td>
                            <td>{{$produit->libelle}}</td>
                            <td>{{$produit->categorie}}</td>
                            <td>{{$produit->prix}} MAD</td>
                            <td>{{$stock[$index]->qte}}</td>
                            <td>
                            <a href="{{route('reception.index')}}" style="color: white" 
                                    class="badge badge-pill badge-danger">
                                {{$stock[$index]->cmd}}
                                </a>
                            </td>
                            
         
                           <td style="font-size: 1.5em">
                           
                            <a style="color: #e85f03" href="/produit/{{$produit->id}}">
                                <i class="ti-pencil""></i></a>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="10" style="text-align: center">Aucun produit enregistré!</td>
                        </tr>
                        
                           @endforelse
                         
                        </tbody>
                        
                    </table>
                    <div class="row">
                        <div class="col-12 d-flex justify-content-center">
                            {{$produits -> links()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>





<div class="container my-4">    
    @can('ecom')
    <div class="modal fade" id="modalStockAdd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header text-center">
                          <h4 class="modal-title w-100 font-weight-bold">Nouveau Produit</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body mx-3">
                            <form class="form-horizontal form-material" method="POST" action="{{route('produit.store')}}" enctype="multipart/form-data">
                                @csrf
                                
                                <div class="form-group">
                                    <label class="col-md-12">Libelle du Produit :</label>
                                    <div class="col-md-12">
                                        <input  value="{{ old('libelle') }}" name="libelle" type="text" placeholder="Libelle" class="form-control form-control-line" required>
                                    </div>
                                </div>
                               
                                <div class="form-group col-md-12">
                                    <label for="example-email" class="col-md-12">Prix (MAD) :</label>
                                    <div class="col-md-12">
                                        <input  value="{{ old('prix') }}" type="number" class="form-control form-control-line" name="prix" >
                                    </div>
                                </div>
                
                                <div class="form-group">
                                    <label class="col-md-12">Description :</label>
                                    <div class="col-md-12">
                                        <textarea  name="description" rows="5" class="form-control form-control-line">{{ old('description') }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Categorie :</label>
                                    <div class="col-sm-12">
                                        <select name="categorie" class="form-control form-control-line" >
                                            <option >Vêtements</option>
                                            <option >Chaussures</option>
                                            <option >Bijoux et accessoires</option>
                                            <option >Produits Cosmétiques</option>
                                            <option >Produits High Tech</option>
                                            <option >Librairie</option>
                                            <option >Maroquinerie</option>
                                            <option >Végétaux</option>
                                            <option >Autres</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                      <input type="file" name="photo" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                                      <label class="custom-file-label" for="inputGroupFile01">choisir une photo</label>
                                    </div>
                                  </div>
                                <div class="form-group">
                                    <div class="modal-footer d-flex justify-content-center">
                                        <button class="btn btn-danger">Ajouter</button>
                                        
                                    </div>
                                </div>
                            </form>
                            @if ($errors->any())
                            <div class="alert alert-dismissible alert-danger">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>
                                        <strong>{{$error}}</strong>
                                        </li>
                                    @endforeach
                                </ul>
                              </div>
                              @endif
                        </div>
            
                      </div>
                    </div>
    </div>
    @endcan
</div>


@endsection

resources/views/produit/show.blade.php
@extends('racine')

@section('title')
{{$produit->libelle}} | {{$produit->reference}}
@endsection



@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-12">
        <h4 class="page-title">Gestion du produit {{$produit->reference}}</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item" aria-current="page"><a href="/produit">Stock</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{$produit->libelle}}</li>

                    </ol>
                </nav>
            </div>
            <div class="row float-right" id="navbar-example3">
              <a onclick="productedit()" href="#from_product_edit" class="btn btn-warning text-white m-r-5">Modifier <i class="fas fa-edit"></i></a>
        
            </div>
        </div>
        
      </div>
    
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->


<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <div class="row">
           
        @if (session()->has('produit'))
        <div class="alert alert-dismissible alert-success col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Succés !</strong> Ce produit à été bien Modifié </a>.
          </div>
        @endif
    </div>    <!-- ============================================================== -->
    <!-- Row -->
    <div class="row">
        
        <!-- Column -->
        <div class="col-lg-4 col-xlg-3 col-md-5">
            <div class="card">
                <div class="card-body">
                <center class="m-t-30">
                    <div class="box">
                        <div class="js--image-preview">
                           <img class="photo_produit" src="/uploads/produit/{{$produit->photo}}" alt="" width="250" height="250">
                            </div>
                       
                      </div>
                    
                        <h4 class="card-title m-t-10">{{$produit->libelle}}</h4>
                        <h6 class="card-subtitle">{{$produit->description}}</h6>
                        <div class="row text-center justify-content-md-center">
                        <div class="col-4"><a href="{{route('produit.index')}}" class="link"><i class="icon-people"></i> <font class="font-medium">{{$stock->qte}} <br>En Stock</font></a></div>
                        <div class="col-4"><a href="{{route('produit.index')}}" class="link"><i class="icon-picture"></i> <font class="font-medium">{{$stock->cmd}} <br>En commande</font></a></div>
                        </div>
                    </center>
                </div>
                <div>
                    <hr> </div>
                {{-- <div class="card-body"> 
                    <h3>Mouvement du stock</h3>
                    <small class="text-muted">Addresse email </small>
                    <h6>test test</h6> <small class="text-muted p-t-30 db">Téléphone</small>
                    <h6>test test</h6> <small class="text-muted p-t-30 db">Addresse</small>
                    <h6>test test</h6>
                    </div> --}}
            </div>
        </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-lg-8 col-xlg-9 col-md-7" data-spy="scroll" data-target="#edit_product" data-offset="0">
            <div class="card" id="from_product_edit">
                <div class="card-body">
                    <form class="form-horizontal form-material" method="POST" action="{{route('produit.update',$produit)}}" enctype="multipart/form-data">
                        @csrf
                        @method("PUT")
                        <fieldset id="fieldset_edit" disabled>
                        <div class="form-group">
                            <label for="libelle" class="col-md-12">Libelle: </label>

                        <div class="col-md-12">
                            <input id="libelle" type="text" class="form-control @error('libelle') is-invalid @enderror" name="libelle" value="{{ $produit->libelle }}" required  autofocus>

                            @error('libelle')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-12">Prix de produit</label>
                            <div class="col-md-12">
                            <input name="prix" type="text" value="{{$produit->prix}}" class="form-control form-control-line">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12">Description</label>
                            <div class="col-md-12">
                            <textarea name="description" rows="5" class="form-control form-control-line">{{$produit->description}}</textarea>
                            </div>
                        </div>
                     
                        <div class="form-group">
                            <label class="col-sm-12">Catégorie :</label>
                            <div class="col-sm-12">
                                <select name="categorie" value="{{$produit->categorie}}" class="form-control form-control-line" >
                                    <option checked>{{$produit->categorie}}</option>
                                    <option >Vêtements</option>
                                    <option >Chaussures</option>
                                    <option >Bijoux et accessoires</option>
                                    <option >Produits Cosmétiques</option>
                                    <option >Produits High Tech</option>
                                    <option >Librairie</option>
                                    <option >Maroquinerie</option>
                                    <option >Végétaux</option>
                                    <option >Autres</option>
                                </select>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                          </div>
                          <div class="custom-file">
                            <input type="file" name="photo" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">choisir une photo</label>
                          </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-success">Modifier</button>
                            </div>
                        </div>
                      </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <!-- Column -->
    </div>

</div>
@endsection

@section('javascript')
    
  <script>
    function productedit() {
  document.getElementById("fieldset_edit").disabled = !document.getElementById("fieldset_edit").disabled;
}
  </script>

@endsection