routes/web.php
<?php

use App\Http\Controllers\ProfilController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;



Route::get('/', 'DashboardController@dash')->name('dashboard');

Route::get('/commandes/{id}/statut', 'CommandeController@changeStatut')->name('commandeStatut');

Route::patch('/commandes/{id}/statut', 'CommandeController@statutAdmin')->name('statut.admin');

Route::get('pdf/{id}','CommandeController@gen')->name('pdf.gen');

Route::get('/search', 'CommandeController@search')->name('commande.search');

Route::get('/commandes/filter', 'CommandeController@filter')->name('commande.filter');

Route::resource('/commandes','CommandeController')->except([
    'create', 'edit'
]);

Route::resource('/produit','ProduitController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::resource('/reception','ReceptionController')->except([
    'create', 'edit'
])->middleware('can:gestion-stock');

Route::get('/reception/{id}/valide','ReceptionController@valide')->name('reception.valide')->middleware('can:manage-users');

Route::get('showFromNotify/{commande}/{notification}' , 'CommandeController@showFromNotify')->name('commandes.showFromNotify');

Route::get('showFromNotify/{reception}/{notification}' , 'ReceptionController@showFromNotify')->name('reception.showFromNotify');


Route::get('/profil', 'ProfilController@index')->name('profil.index');

Route::match(['put', 'patch'],'/profil/{user}', 'ProfilController@update')->name('profil.update');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/bonlivraison','BonLivraisonController')->only([
    'index', 'store'
]);

Route::get('/bonlivraison/{id}/infos','BonLivraisonController@infos')->name('bon.infos');

Route::get('/bonlivraison/{id}/pdf','BonLivraisonController@gen')->name('bon.gen');

Route::get('/bonlivraison/{id}/details','BonLivraisonController@search')->name('bon.search');

Route::resource('/facture','FactureController')->only([
    'index', 'store'
]);

Route::get('/facture/{id}/pdf','FactureController@gen')->name('facture.gen');

Route::get('/facture/{id}/details','FactureController@search')->name('facture.search');

Route::get('/facture/{id}/infos','FactureController@infos')->name('facture.infos');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users','UsersController',['except' => ['show','create','store']]);
});

Route::get('/facture/{id}/send','EmailController@sendFacture')->name('email.facture')->middleware('can:ramassage-commande');

Route::get('/inbox','NotificationController@index')->name('inbox.index');
Route::get('/{notifications}/show','NotificationController@show')->name('inbox.show');
Route::get('/{notifications}/delete','NotificationController@destroy')->name('inbox.destroy');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{

    use SoftDeletes;

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','description','telephone','adresse','image','ville',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->BelongsToMany('App\Role');
    }

    public function hasAnyRoles($roles){
        if($this->roles()->whereIn('name',$roles)->first()) {return true;}
        return false;
    }

    public function hasRole($role){
        if($this->roles()->where('name',$role)->first()) {return true;}
        return false;
    }

    public function commandes(){
        return $this->hasMany('App\Commande');
    }

    public function produits(){
        return $this->hasMany('App\Produit');
    }

    public function mouvements(){
        return $this->hasMany('App\Mouvement');
    }

    public function receptions()
    {
        return $this->hasMany('App\Reception');
    }


    public function bonLivraisons()
    {
        return $this->hasMany('App\BonLivraison');
    }

    public function factures()
    {
        return $this->hasMany('App\Facture');
    }

    public function statuts()
    {
        return $this->hasMany('App\Statut');
    }

    

    public static function boot(){
        parent::boot();

        static::deleting(function(User $user){
            $user->commandes()->delete();
        });

    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class UsersController extends Controller
{

 /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        //dd($users);
        return view('admin.users.index')->with('users',$users);
    }

  

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(Gate::denies('edit-users')){
            return redirect(route('admin.users.index'));
        }

        $roles = Role::all();
        //dd($user->roles()->get()->pluck('name')->toArray());
        return view('admin.users.edit')->with([
            'user'=>$user,
            'roles'=>$roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {   
        //dd($user);
        

        if(Gate::denies('edit-users')){
            return redirect(route('admin.users.index'));
        }
       // dd($request->roles);
       $user->roles()->sync($request->roles);
       $user->image=$request->image;
       $user->name=$request->name;
       $user->email=$request->email;
       $user->description = $request->description;
       $user->save();
       
       return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if(Gate::denies('delete-users')){
            return redirect(route('admin.users.index'));
        }

        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');

    }
}

resources/views/admin/users/edit.blade.php
@extends('racine')

@section('title')
   Gestion des Utilisateurs
@endsection



@section('style')
    <style>
        .page-link {
            color: #e85f03 !important;
        }
        .page-item.active .page-link {
            
            background-color: #e85f03 !important;
            border-color: #e85f03 !important;
            color: #fff !important;
        }
    </style>
@endsection


@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-5">
            <h4 class="page-title">Gestion des Utilisateurs</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item"><a href="/admin/users">Utilisateurs</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{$user->name}}</li>
                    </ol>
                </nav>
            </div>
        </div>
    
    </div>
</div>

<div class="container-fluid">
    
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Modifier l'utilisateur: {{ $user->name}}</div>

                <div class="card-body">
                <form method="POST" action="{{route('admin.users.update',$user)}}">
                    @csrf
                    @method("PUT")
                    <div class="form-group row">
                        <label for="name" class="col-md-2 col-form-label text-md-right">Nom & Prénom: </label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required  autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-2 col-form-label text-md-right">Email: </label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required>

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label text-md-right">Url de l'image</label>
                        <div class="col-md-6">
                            <input name="image" type="text" value="{{$user->image}}"class="form-control form-control-line">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label text-md-right">ICE</label>
                        <div class="col-md-6">
                            <input name="description" type="text" value="{{$user->description}}"class="form-control form-control-line">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="roles" class="col-md-2 col-form-label text-md-right">Rôles: </label>
                        <div class="col-md-6">
                    @foreach ($roles as $role)
                        <div class="form-check">
                            @if (in_array($role->name, $user->roles()->get()->pluck('name')->toArray()) )
                            <input type="radio" name="roles[]" value="{{$role->id}}" id="{{$role->name}}" checked>
                            @else
                            <input type="radio" name="roles[]" value="{{$role->id}}" id="{{$role->name}}">
                            @endif
                            <label for="{{$role->name}}">
                                @switch($role->name)
                                    @case('client')
                                     Collecte, Livraison
                                        @break
                                    @case('ecom')
                                    Collecte, livraison, stockage
                                        @break
                                    @default
                                    {{$role->name}}
                                @endswitch
                            </label>
                        </div>
                    @endforeach
                    </div>
                </div>
                    <button type="submit" class="btn btn-primary">Modifier</button>
                </form>
                  
                     
                  
                </div>
            </div>
        </div>
    </div>

</div>




@endsection

@section('javascript')
    @if ($errors->any())
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#modalSubscriptionForm').modal('show');
            });
        </script>
    @endif
@endsection

resources/views/admin/users/index.blade.php
@extends('racine')

@section('title')
   Gestion des Utilisateurs
@endsection



@section('style')
    <style>
        .page-link {
            color: #e85f03 !important;
        }
        .page-item.active .page-link {
            
            background-color: #e85f03 !important;
            border-color: #e85f03 !important;
            color: #fff !important;
        }
    </style>
@endsection


@section('content')
<div class="page-breadcrumb">
    <div class="row align-items-center">
        <div class="col-5">
            <h4 class="page-title">Gestion des Utilisateurs</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Quickoo</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Utilisateurs</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-7">
            <div class="text-right upgrade-btn">
            <a  class="btn btn-danger text-white" href="{{route('register')}}"><i class="fa fa-plus-square"></i> Ajouter</a>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    @if (session()->has('register'))
        <div class="alert alert-dismissible alert-success col-12">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Oupss !</strong> l'utilisateur : {{session()->get('register')}} à été bien enregister et mail envoyé </a>.
          </div>
        @endif
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">{{ __('Utilisateurs Quickoo') }}</div>
                
                <div class="card-body" >
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nom & Prénom</th>
                                <th scope="col">Email</th>
                                <th scope="col">Rôles</th>
                                @can('edit-users')
                                <th scope="col">Action</th>
                                @endcan
                                
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                              <tr>
                                <th scope="row"><img src="{{$user->image}}" alt="user" class="rounded-circle" width="31"></a></th>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{ implode(', ' , $user->roles()->get()->pluck('name')->toArray() )}}</td>
                                @can('edit-users')
                                <td>
                                    <a href="{{route('admin.users.edit',$user->id)}}">
                                       <button class="btn btn-primary float-lef"><i class="mdi mdi-account-edit"></i></button>
                                   </a>
                                   <a href="{{route('admin.users.destroy',$user->id)}}">
                                       <form action="{{route('admin.users.destroy',$user->id)}}" method="POST" class="float-left">
                                           @csrf
                                           @method("DELETE")
                                           <button class="btn btn-warning"><i class="mdi mdi-delete"></i></button>
                                       </form>
                                       
                                   </a>
                               </td>
                                @endcan
                                
                                </tr>
                              @endforeach
    
                            </tbody>
                          </table>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

</div>




@endsection

@section('javascript')
    @if ($errors->any())
        <script type="text/javascript">
            $(window).on('load',function(){
                $('#modalSubscriptionForm').modal('show');
            });
        </script>
    @endif
@endsection